### ISSUE TITLE
個人計畫與估計時程

### ISSUE THREAD

**Issue by cwpeng** [MCplyNiz/Timeline#2]
目前我的開發計畫順序如下：

1. 個人專案：完成一個在 Chrome Web Store 上的簡單服務。
2. 本專案：完成 Timeline 讀取 Facebook 帳戶資料功能。
3. 心理系專案：完成一個 Android App 的初步樣貌。

我估計大約兩個星期以內，完成這個專案的第一個目標。
然後再兩個星期後，大約一月底，可以繼續進行這個專案的下個目標。

**Comment by cwpeng** [comment]
Facebook 新版本的 API，無法在當事人未授權的情況下，抓到該用戶的公開資料。
也就是說若陳為廷沒有授權給我們，我們就無法用程式抓到他貼的文章，就算是公開的也不行。

------

被卡住 Orz
可能需要新的資料來源，和整合後的用途想像。

**Comment by MitsunChieh** [comment]
擱置吧。
